insert into vehicle_makes (name) values
  ('Alfa Romeo'), ('Audi'), ('BMW'), ('Chevrolet'), ('Chrysler'), ('Citroen'),
  ('Cupra'), ('Dacia'), ('Dodge'), ('Fiat'), ('Ford'), ('Honda'), ('Hyundai'),
  ('Jaguar'), ('Jeep'), ('Kia'), ('Lancia'), ('Land Rover'), ('Lexus'), ('Mazda'),
  ('Mercedes'), ('Mini'), ('Mitsubishi'), ('Nissan'), ('Opel'), ('Peugeot'),
  ('Porsche'), ('Renault'), ('Saab'), ('Seat'), ('Skoda'), ('Smart'), ('Subaru'),
  ('Suzuki'), ('Tesla'), ('Toyota'), ('Volkswagen'), ('Volvo'), ('Porsche'),
  ('Lexus')
on conflict (name) do nothing;

insert into vehicle_models (make_id, name, category)
select m.id, x.name, x.category
from vehicle_makes m
join (values
  ('Audi', 'A3', 'passenger'),
  ('Audi', 'A4', 'passenger'),
  ('Audi', 'A6', 'passenger'),
  ('Audi', 'Q2', 'crossover'),
  ('Audi', 'Q3', 'crossover'),
  ('Audi', 'Q5', 'crossover'),
  ('Audi', 'Q7', 'crossover'),
  ('Audi', 'Q8', 'crossover'),
  ('BMW', '1 Series', 'passenger'),
  ('BMW', '3 Series', 'passenger'),
  ('BMW', '5 Series', 'passenger'),
  ('BMW', 'X1', 'crossover'),
  ('BMW', 'X3', 'crossover'),
  ('BMW', 'X5', 'crossover'),
  ('BMW', 'X6', 'crossover'),
  ('BMW', '2 Series Active Tourer', 'minivan'),
  ('Citroen', 'C3', 'passenger'),
  ('Citroen', 'C4', 'passenger'),
  ('Citroen', 'C5', 'passenger'),
  ('Citroen', 'C3 Aircross', 'crossover'),
  ('Citroen', 'C5 Aircross', 'crossover'),
  ('Citroen', 'Berlingo', 'commercial'),
  ('Citroen', 'Jumpy', 'commercial'),
  ('Citroen', 'Jumper', 'commercial'),
  ('Cupra', 'Leon', 'passenger'),
  ('Cupra', 'Formentor', 'crossover'),
  ('Cupra', 'Ateca', 'crossover'),
  ('Dacia', 'Sandero', 'passenger'),
  ('Dacia', 'Logan', 'passenger'),
  ('Dacia', 'Duster', 'crossover'),
  ('Dacia', 'Jogger', 'minivan'),
  ('Fiat', '500', 'passenger'),
  ('Fiat', 'Tipo', 'passenger'),
  ('Fiat', 'Panda', 'passenger'),
  ('Fiat', '500X', 'crossover'),
  ('Fiat', 'Doblo', 'commercial'),
  ('Fiat', 'Ducato', 'commercial'),
  ('Ford', 'Fiesta', 'passenger'),
  ('Ford', 'Focus', 'passenger'),
  ('Ford', 'Mondeo', 'passenger'),
  ('Ford', 'Puma', 'crossover'),
  ('Ford', 'Kuga', 'crossover'),
  ('Ford', 'Explorer', 'crossover'),
  ('Ford', 'S-Max', 'minivan'),
  ('Ford', 'Galaxy', 'minivan'),
  ('Ford', 'Tourneo', 'minivan'),
  ('Ford', 'Transit', 'commercial'),
  ('Ford', 'Transit Connect', 'commercial'),
  ('Ford', 'Ranger', 'commercial'),
  ('Honda', 'Civic', 'passenger'),
  ('Honda', 'Accord', 'passenger'),
  ('Honda', 'Jazz', 'passenger'),
  ('Honda', 'HR-V', 'crossover'),
  ('Honda', 'CR-V', 'crossover'),
  ('Hyundai', 'i20', 'passenger'),
  ('Hyundai', 'i30', 'passenger'),
  ('Hyundai', 'Elantra', 'passenger'),
  ('Hyundai', 'Kona', 'crossover'),
  ('Hyundai', 'Tucson', 'crossover'),
  ('Hyundai', 'Santa Fe', 'crossover'),
  ('Hyundai', 'Staria', 'minivan'),
  ('Jeep', 'Renegade', 'crossover'),
  ('Jeep', 'Compass', 'crossover'),
  ('Jeep', 'Cherokee', 'crossover'),
  ('Jeep', 'Grand Cherokee', 'crossover'),
  ('Jeep', 'Wrangler', 'crossover'),
  ('Kia', 'Rio', 'passenger'),
  ('Kia', 'Ceed', 'passenger'),
  ('Kia', 'Stonic', 'crossover'),
  ('Kia', 'Sportage', 'crossover'),
  ('Kia', 'Sorento', 'crossover'),
  ('Kia', 'Niro', 'crossover'),
  ('Kia', 'Carnival', 'minivan'),
  ('Land Rover', 'Defender', 'crossover'),
  ('Land Rover', 'Discovery', 'crossover'),
  ('Land Rover', 'Range Rover Evoque', 'crossover'),
  ('Land Rover', 'Range Rover Sport', 'crossover'),
  ('Lexus', 'IS', 'passenger'),
  ('Lexus', 'ES', 'passenger'),
  ('Lexus', 'UX', 'crossover'),
  ('Lexus', 'NX', 'crossover'),
  ('Lexus', 'RX', 'crossover'),
  ('Mazda', '2', 'passenger'),
  ('Mazda', '3', 'passenger'),
  ('Mazda', '6', 'passenger'),
  ('Mazda', 'CX-3', 'crossover'),
  ('Mazda', 'CX-30', 'crossover'),
  ('Mazda', 'CX-5', 'crossover'),
  ('Mazda', 'CX-60', 'crossover'),
  ('Mercedes', 'A-Class', 'passenger'),
  ('Mercedes', 'C-Class', 'passenger'),
  ('Mercedes', 'E-Class', 'passenger'),
  ('Mercedes', 'CLA', 'passenger'),
  ('Mercedes', 'GLA', 'crossover'),
  ('Mercedes', 'GLB', 'crossover'),
  ('Mercedes', 'GLC', 'crossover'),
  ('Mercedes', 'GLE', 'crossover'),
  ('Mercedes', 'B-Class', 'minivan'),
  ('Mercedes', 'V-Class', 'minivan'),
  ('Mercedes', 'Vito', 'commercial'),
  ('Mercedes', 'Sprinter', 'commercial'),
  ('Mini', 'Cooper', 'passenger'),
  ('Mini', 'Countryman', 'crossover'),
  ('Mitsubishi', 'Lancer', 'passenger'),
  ('Mitsubishi', 'ASX', 'crossover'),
  ('Mitsubishi', 'Outlander', 'crossover'),
  ('Mitsubishi', 'Eclipse Cross', 'crossover'),
  ('Mitsubishi', 'L200', 'commercial'),
  ('Nissan', 'Micra', 'passenger'),
  ('Nissan', 'Leaf', 'passenger'),
  ('Nissan', 'Qashqai', 'crossover'),
  ('Nissan', 'Juke', 'crossover'),
  ('Nissan', 'X-Trail', 'crossover'),
  ('Nissan', 'Navara', 'commercial'),
  ('Opel', 'Corsa', 'passenger'),
  ('Opel', 'Astra', 'passenger'),
  ('Opel', 'Insignia', 'passenger'),
  ('Opel', 'Mokka', 'crossover'),
  ('Opel', 'Crossland', 'crossover'),
  ('Opel', 'Grandland', 'crossover'),
  ('Opel', 'Zafira', 'crossover'),
  ('Opel', 'Combo', 'commercial'),
  ('Opel', 'Vivaro', 'commercial'),
  ('Peugeot', '208', 'passenger'),
  ('Peugeot', '308', 'passenger'),
  ('Peugeot', '508', 'passenger'),
  ('Peugeot', '2008', 'crossover'),
  ('Peugeot', '3008', 'crossover'),
  ('Peugeot', '5008', 'crossover'),
  ('Peugeot', 'Rifter', 'minivan'),
  ('Peugeot', 'Partner', 'commercial'),
  ('Peugeot', 'Expert', 'commercial'),
  ('Peugeot', 'Boxer', 'commercial'),
  ('Porsche', '911', 'passenger'),
  ('Porsche', 'Panamera', 'passenger'),
  ('Porsche', 'Macan', 'crossover'),
  ('Porsche', 'Cayenne', 'crossover'),
  ('Renault', 'Clio', 'passenger'),
  ('Renault', 'Megane', 'passenger'),
  ('Renault', 'Captur', 'crossover'),
  ('Renault', 'Kadjar', 'crossover'),
  ('Renault', 'Austral', 'crossover'),
  ('Renault', 'Scenic', 'minivan'),
  ('Renault', 'Espace', 'minivan'),
  ('Renault', 'Kangoo', 'commercial'),
  ('Renault', 'Trafic', 'commercial'),
  ('Renault', 'Master', 'commercial'),
  ('Seat', 'Ibiza', 'passenger'),
  ('Seat', 'Leon', 'passenger'),
  ('Seat', 'Arona', 'crossover'),
  ('Seat', 'Ateca', 'crossover'),
  ('Seat', 'Tarraco', 'crossover'),
  ('Seat', 'Alhambra', 'minivan'),
  ('Skoda', 'Fabia', 'passenger'),
  ('Skoda', 'Octavia', 'passenger'),
  ('Skoda', 'Superb', 'passenger'),
  ('Skoda', 'Scala', 'passenger'),
  ('Skoda', 'Kamiq', 'crossover'),
  ('Skoda', 'Karoq', 'crossover'),
  ('Skoda', 'Kodiaq', 'crossover'),
  ('Skoda', 'Enyaq', 'crossover'),
  ('Skoda', 'Roomster', 'minivan'),
  ('Subaru', 'Impreza', 'passenger'),
  ('Subaru', 'XV', 'crossover'),
  ('Subaru', 'Forester', 'crossover'),
  ('Subaru', 'Outback', 'crossover'),
  ('Suzuki', 'Swift', 'passenger'),
  ('Suzuki', 'Vitara', 'crossover'),
  ('Suzuki', 'S-Cross', 'crossover'),
  ('Suzuki', 'Jimny', 'crossover'),
  ('Tesla', 'Model 3', 'passenger'),
  ('Tesla', 'Model S', 'passenger'),
  ('Tesla', 'Model Y', 'crossover'),
  ('Tesla', 'Model X', 'crossover'),
  ('Toyota', 'Yaris', 'passenger'),
  ('Toyota', 'Corolla', 'passenger'),
  ('Toyota', 'Camry', 'passenger'),
  ('Toyota', 'Prius', 'passenger'),
  ('Toyota', 'C-HR', 'crossover'),
  ('Toyota', 'RAV4', 'crossover'),
  ('Toyota', 'Highlander', 'crossover'),
  ('Toyota', 'Land Cruiser', 'crossover'),
  ('Toyota', 'Proace', 'commercial'),
  ('Toyota', 'Hilux', 'commercial'),
  ('Volkswagen', 'Polo', 'passenger'),
  ('Volkswagen', 'Golf', 'passenger'),
  ('Volkswagen', 'Passat', 'passenger'),
  ('Volkswagen', 'Arteon', 'passenger'),
  ('Volkswagen', 'T-Cross', 'crossover'),
  ('Volkswagen', 'T-Roc', 'crossover'),
  ('Volkswagen', 'Tiguan', 'crossover'),
  ('Volkswagen', 'Touareg', 'crossover'),
  ('Volkswagen', 'Touran', 'minivan'),
  ('Volkswagen', 'Sharan', 'minivan'),
  ('Volkswagen', 'Multivan', 'minivan'),
  ('Volkswagen', 'Caddy', 'commercial'),
  ('Volkswagen', 'Transporter', 'commercial'),
  ('Volkswagen', 'Crafter', 'commercial'),
  ('Volvo', 'S60', 'passenger'),
  ('Volvo', 'S90', 'passenger'),
  ('Volvo', 'V60', 'passenger'),
  ('Volvo', 'V90', 'passenger'),
  ('Volvo', 'XC40', 'crossover'),
  ('Volvo', 'XC60', 'crossover'),
  ('Volvo', 'XC90', 'crossover'),
  ('Alfa Romeo', 'Giulia', 'passenger'),
  ('Alfa Romeo', 'Stelvio', 'crossover'),
  ('Alfa Romeo', 'Tonale', 'crossover'),
  ('Jaguar', 'XE', 'passenger'),
  ('Jaguar', 'XF', 'passenger'),
  ('Jaguar', 'E-Pace', 'crossover'),
  ('Jaguar', 'F-Pace', 'crossover'),
  ('Chevrolet', 'Cruze', 'passenger'),
  ('Chevrolet', 'Captiva', 'crossover'),
  ('Chrysler', '300C', 'passenger'),
  ('Chrysler', 'Voyager', 'minivan'),
  ('Dodge', 'Journey', 'crossover'),
  ('Lancia', 'Ypsilon', 'passenger'),
  ('Saab', '9-3', 'passenger'),
  ('Saab', '9-5', 'passenger'),
  ('Smart', 'Fortwo', 'passenger'),
  ('Smart', 'Forfour', 'passenger'),
  ('Honda', 'Pilot', 'crossover')
) as x(make, name, category) on x.make = m.name
on conflict (make_id, name) do update set category = excluded.category;
